version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=3 --threads=3 --bind 0.0.0.0:5000 app:app
    container_name: auto-test-app-prod
    restart: always
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: auto-test-db-prod
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

  nginx:
    build: ./services/nginx
    container_name: auto-test-nginx-prod
    restart: always
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  pgadmin:


networks:
  default:
    external:
      name: automation-testing-network
